"use client";
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
export function MetricCard({label,value,sub}:{label:string;value:any;sub?:string}){return <div className="panel p-5"><div className="muted text-xs">{label}</div><div className="text-3xl font-bold mt-2">{value}</div>{sub&&<div className="muted text-xs mt-2">{sub}</div>}</div>}
export function SeverityBadge({severity}:{severity:string}){return <span className={`sev sev-${severity.toLowerCase()}`}>{severity}</span>}
export function ConfidenceBadge({confidence}:{confidence:string}){return <span className="sev text-[#9ed8ff]">CONF {confidence}</span>}
export function SecurityScore({score}:{score:number|null}){return <div className="panel p-6 grid place-items-center min-h-[220px]"><div className="muted text-xs mb-3">DETERMINISTIC SECURITY SCORE</div><div className="text-7xl font-black glow">{score===null?"—":Math.round(score)}</div><div className="muted text-xs mt-2">{score===null?"No completed scan yet":"/ 100 · AI cannot alter this score"}</div></div>}
export function TerminalLog({events}:{events:any[]}){return <div className="panel p-4 font-mono text-xs h-64 overflow-auto">{events.map((e,i)=><div key={i} className="mb-1"><span className="muted">[{new Date(e.created_at).toLocaleTimeString()}]</span> <span className={e.level==='ERROR'?'text-red-300':'text-[#00ff88]'}>{e.level||'INFO'}</span> {e.message}</div>)}</div>}
export function AuthGate(){return null}
export function Loading(){return <div className="muted py-12 text-center">Loading security telemetry…</div>}
export function ErrorBox({error}:{error:string}){return <div className="panel border-red-900/60 p-4 text-red-300">{error}</div>}

export function FindingCard({finding}:{finding:any}){return <div className="panel p-4"><div className="flex gap-2 items-center"><SeverityBadge severity={finding.severity}/><ConfidenceBadge confidence={finding.confidence}/><span className="font-bold">{finding.title}</span></div><p className="text-sm muted mt-2">{finding.description}</p></div>}
export function FindingsTable({findings}:{findings:any[]}){return <div className="panel overflow-auto"><table className="w-full text-sm"><tbody>{findings.map(f=><tr key={f.id} className="border-b border-[#17352a]"><td className="p-3">{f.title}</td><td className="p-3"><SeverityBadge severity={f.severity}/></td><td className="p-3"><ConfidenceBadge confidence={f.confidence}/></td></tr>)}</tbody></table></div>}
export function ScanProgress({status,current}:{status:string;current?:string}){return <div className="panel p-4"><div className="flex justify-between text-xs"><span>{status}</span><span className="text-[#00ff88]">{current||'—'}</span></div><div className="h-2 bg-black/30 rounded mt-3 overflow-hidden"><div className="h-full bg-[#00ff88]" style={{width:status==='COMPLETED'?'100%':status==='FAILED'||status==='CANCELLED'?'0%':'58%'}}/></div></div>}
export const ScanTimeline=TerminalLog;
export function TargetCard({target}:{target:any}){return <div className="panel p-5"><div className="font-bold">{target.name}</div><div className="muted text-sm">{target.root_domain}</div><div className="text-xs text-[#00ff88] mt-3">{target.authorization_status}</div></div>}
export function ActivityFeed({items}:{items:any[]}){return <div className="panel p-4 space-y-2">{items.map((x,i)=><div key={i} className="text-xs"><span className="muted">{x.created_at}</span> · {x.message||x.action}</div>)}</div>}
export function CloudflareStatus({connected}:{connected:boolean}){return <div className="panel p-4"><div className="muted text-xs">CLOUDFLARE</div><div className={connected?'text-[#00ff88]':'text-red-300'}>{connected?'CONNECTED':'NOT CONNECTED'}</div></div>}
export function AIAnalysisCard({analysis}:{analysis:any}){return <div className="panel p-5"><div className="text-[#00ff88]">{analysis?.provider||'AI'} · {analysis?.status||'—'}</div><p className="mt-3 text-sm">{analysis?.output?.summary||'No analysis output yet.'}</p></div>}
export function EvidenceViewer({evidence}:{evidence:any}){return <pre className="panel p-4 text-xs whitespace-pre-wrap overflow-auto">{JSON.stringify(evidence,null,2)}</pre>}
export function ReportPreview({report}:{report:any}){return <div className="panel p-5 text-sm"><div className="font-bold">Report</div><div className="muted mt-2">{report?.status||'—'} · {report?.format||'—'}</div></div>}
export function SecurityChart({data}:{data:Record<string,number>}){const max=Math.max(1,...Object.values(data));return <div className="panel p-5 space-y-3">{Object.entries(data).map(([k,v])=><div key={k}><div className="flex justify-between text-xs"><span>{k}</span><span>{v}</span></div><div className="h-2 bg-black/30 rounded mt-1"><div className="h-full bg-[#00ff88] rounded" style={{width:`${(v/max)*100}%`}}/></div></div>)}</div>}
