"""initial CyberSentinel schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def uuid_col(): return postgresql.UUID(as_uuid=True)

def upgrade():
    role = postgresql.ENUM('ADMIN','ANALYST','VIEWER', name='role', create_type=True)
    scanstatus = postgresql.ENUM('QUEUED','VALIDATING','RUNNING','ANALYZING','COMPLETED','FAILED','CANCELLED', name='scanstatus', create_type=True)
    severity = postgresql.ENUM('INFO','LOW','MEDIUM','HIGH','CRITICAL', name='severity', create_type=True)
    confidence = postgresql.ENUM('LOW','MEDIUM','HIGH', name='confidence', create_type=True)
    bind=op.get_bind(); role.create(bind,checkfirst=True); scanstatus.create(bind,checkfirst=True); severity.create(bind,checkfirst=True); confidence.create(bind,checkfirst=True)
    op.create_table('users',sa.Column('id',uuid_col(),primary_key=True),sa.Column('email',sa.String(320),nullable=False,unique=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('password_hash',sa.String(512),nullable=False),sa.Column('role',role,nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('failed_logins',sa.Integer(),nullable=False,server_default='0'),sa.Column('locked_until',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_users_email','users',['email'],unique=False)
    op.create_table('sessions',sa.Column('id',uuid_col(),primary_key=True),sa.Column('user_id',uuid_col(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('token_hash',sa.String(128),nullable=False,unique=True),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('revoked_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_sessions_user_id','sessions',['user_id']); op.create_index('ix_sessions_expires_at','sessions',['expires_at']); op.create_index('ix_sessions_token_hash','sessions',['token_hash'])
    op.create_table('targets',sa.Column('id',uuid_col(),primary_key=True),sa.Column('owner_id',uuid_col(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(160),nullable=False),sa.Column('root_domain',sa.String(253),nullable=False),sa.Column('authorization_status',sa.String(32),nullable=False,server_default='PENDING'),sa.Column('notes',sa.Text()),sa.Column('scan_config',postgresql.JSONB(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_targets_owner_id','targets',['owner_id']); op.create_index('ix_targets_root_domain','targets',['root_domain'])
    op.create_table('target_scopes',sa.Column('id',uuid_col(),primary_key=True),sa.Column('target_id',uuid_col(),sa.ForeignKey('targets.id',ondelete='CASCADE'),nullable=False),sa.Column('kind',sa.String(32),nullable=False),sa.Column('value',sa.String(512),nullable=False),sa.Column('allowed',sa.Boolean(),nullable=False,server_default=sa.true()),sa.UniqueConstraint('target_id','kind','value',name='uq_target_scope')); op.create_index('ix_target_scopes_target_id','target_scopes',['target_id'])
    op.create_table('scans',sa.Column('id',uuid_col(),primary_key=True),sa.Column('target_id',uuid_col(),sa.ForeignKey('targets.id',ondelete='CASCADE'),nullable=False),sa.Column('requested_by',uuid_col(),sa.ForeignKey('users.id'),nullable=False),sa.Column('status',scanstatus,nullable=False),sa.Column('profile',sa.String(64),nullable=False),sa.Column('scope_snapshot',postgresql.JSONB(),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('ended_at',sa.DateTime(timezone=True)),sa.Column('current_module',sa.String(64)),sa.Column('modules_completed',sa.Integer(),nullable=False,server_default='0'),sa.Column('final_score',sa.Float()),sa.Column('error',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_scans_target_id','scans',['target_id']); op.create_index('ix_scans_requested_by','scans',['requested_by']); op.create_index('ix_scans_status','scans',['status'])
    op.create_table('scan_modules',sa.Column('id',uuid_col(),primary_key=True),sa.Column('scan_id',uuid_col(),sa.ForeignKey('scans.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(80),nullable=False),sa.Column('status',sa.String(32),nullable=False,server_default='QUEUED'),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('ended_at',sa.DateTime(timezone=True)),sa.Column('error',sa.Text())); op.create_index('ix_scan_modules_scan_id','scan_modules',['scan_id'])
    op.create_table('scan_events',sa.Column('id',uuid_col(),primary_key=True),sa.Column('scan_id',uuid_col(),sa.ForeignKey('scans.id',ondelete='CASCADE'),nullable=False),sa.Column('level',sa.String(16),nullable=False,server_default='INFO'),sa.Column('message',sa.Text(),nullable=False),sa.Column('event_type',sa.String(64),nullable=False,server_default='scan'),sa.Column('metadata',postgresql.JSONB(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_scan_events_scan_id','scan_events',['scan_id']); op.create_index('ix_scan_events_created_at','scan_events',['created_at'])
    op.create_table('findings',sa.Column('id',uuid_col(),primary_key=True),sa.Column('scan_id',uuid_col(),sa.ForeignKey('scans.id',ondelete='CASCADE'),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('category',sa.String(80),nullable=False),sa.Column('severity',severity,nullable=False),sa.Column('confidence',confidence,nullable=False),sa.Column('cwe',sa.String(32)),sa.Column('owasp_category',sa.String(64)),sa.Column('description',sa.Text(),nullable=False),sa.Column('evidence',postgresql.JSONB(),nullable=False),sa.Column('affected_url',sa.String(2048)),sa.Column('impact',sa.Text(),nullable=False),sa.Column('remediation',sa.Text(),nullable=False),sa.Column('references',postgresql.JSONB(),nullable=False),sa.Column('detected_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_findings_scan_id','findings',['scan_id']); op.create_index('ix_findings_severity','findings',['severity']); op.create_index('ix_findings_confidence','findings',['confidence']); op.create_index('ix_findings_detected_at','findings',['detected_at']); op.create_index('ix_findings_scan_severity','findings',['scan_id','severity'])
    op.create_table('finding_evidence',sa.Column('id',uuid_col(),primary_key=True),sa.Column('finding_id',uuid_col(),sa.ForeignKey('findings.id',ondelete='CASCADE'),nullable=False),sa.Column('kind',sa.String(64),nullable=False),sa.Column('source',sa.String(64),nullable=False),sa.Column('content',postgresql.JSONB(),nullable=False),sa.Column('captured_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_finding_evidence_finding_id','finding_evidence',['finding_id'])
    op.create_table('cloudflare_connections',sa.Column('id',uuid_col(),primary_key=True),sa.Column('user_id',uuid_col(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('account_id',sa.String(64)),sa.Column('zone_id',sa.String(64)),sa.Column('token_encrypted',sa.Text(),nullable=False),sa.Column('label',sa.String(160),nullable=False),sa.Column('last_tested_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_cloudflare_connections_user_id','cloudflare_connections',['user_id'])
    op.create_table('ai_analyses',sa.Column('id',uuid_col(),primary_key=True),sa.Column('scan_id',uuid_col(),sa.ForeignKey('scans.id',ondelete='CASCADE'),nullable=False),sa.Column('provider',sa.String(64),nullable=False),sa.Column('model',sa.String(160),nullable=False),sa.Column('status',sa.String(32),nullable=False,server_default='QUEUED'),sa.Column('input_evidence',postgresql.JSONB(),nullable=False),sa.Column('output',postgresql.JSONB()),sa.Column('confidence',sa.Float()),sa.Column('error',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_ai_analyses_scan_id','ai_analyses',['scan_id'])
    op.create_table('reports',sa.Column('id',uuid_col(),primary_key=True),sa.Column('scan_id',uuid_col(),sa.ForeignKey('scans.id',ondelete='CASCADE'),nullable=False),sa.Column('format',sa.String(16),nullable=False),sa.Column('status',sa.String(32),nullable=False,server_default='QUEUED'),sa.Column('file_path',sa.String(2048)),sa.Column('content',sa.Text()),sa.Column('blob',sa.LargeBinary()),sa.Column('created_by',uuid_col(),sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_reports_scan_id','reports',['scan_id'])
    op.create_table('audit_logs',sa.Column('id',uuid_col(),primary_key=True),sa.Column('user_id',uuid_col(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('action',sa.String(80),nullable=False),sa.Column('resource_type',sa.String(80)),sa.Column('resource_id',sa.String(64)),sa.Column('ip_address',sa.String(64)),sa.Column('details',postgresql.JSONB(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_audit_logs_user_id','audit_logs',['user_id']); op.create_index('ix_audit_logs_action','audit_logs',['action']); op.create_index('ix_audit_logs_created_at','audit_logs',['created_at'])
    op.create_table('system_settings',sa.Column('key',sa.String(128),primary_key=True),sa.Column('value',sa.Text(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for t in ['system_settings','audit_logs','reports','ai_analyses','cloudflare_connections','finding_evidence','findings','scan_events','scan_modules','scans','target_scopes','targets','sessions','users']:
        op.drop_table(t)
    bind=op.get_bind()
    for typ in ['confidence','severity','scanstatus','role']:
        op.execute(sa.text(f'DROP TYPE IF EXISTS {typ}'))
