export const API_URL=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
export type User={id:string;email:string;name:string;role:"ADMIN"|"ANALYST"|"VIEWER"};
function tokens(){return {access:typeof window!=="undefined"?localStorage.getItem("cs_access"):null,refresh:typeof window!=="undefined"?localStorage.getItem("cs_refresh"):null}}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{
 const t=tokens(); const headers=new Headers(init.headers); headers.set("Content-Type","application/json"); if(t.access) headers.set("Authorization",`Bearer ${t.access}`);
 let r=await fetch(API_URL+path,{...init,headers,cache:"no-store"});
 if(r.status===401&&t.refresh){const rr=await fetch(API_URL+"/api/auth/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refresh_token:t.refresh})}); if(rr.ok){const x=await rr.json(); localStorage.setItem("cs_access",x.access_token);localStorage.setItem("cs_refresh",x.refresh_token);headers.set("Authorization",`Bearer ${x.access_token}`);r=await fetch(API_URL+path,{...init,headers,cache:"no-store"})}}
 if(!r.ok){let e:any={}; try{e=await r.json()}catch{}; throw new Error(e.message||e.detail||`HTTP ${r.status}`)}
 return r.status===204?undefined as T:r.json();
}
export const api={
 login:(x:any)=>request<any>("/api/auth/login",{method:"POST",body:JSON.stringify(x)}),register:(x:any)=>request<any>("/api/auth/register",{method:"POST",body:JSON.stringify(x)}),me:()=>request<User>("/api/auth/me"),
 summary:()=>request<any>("/api/dashboard/summary"),targets:()=>request<any[]>("/api/targets"),createTarget:(x:any)=>request<any>("/api/targets",{method:"POST",body:JSON.stringify(x)}),updateTarget:(id:string,x:any)=>request<any>(`/api/targets/${id}`,{method:"PATCH",body:JSON.stringify(x)}),target:(id:string)=>request<any>(`/api/targets/${id}`),
 scans:()=>request<any[]>("/api/scans"),scan:(id:string)=>request<any>(`/api/scans/${id}`),createScan:(x:any)=>request<any>("/api/scans",{method:"POST",body:JSON.stringify(x)}),cancelScan:(id:string)=>request<any>(`/api/scans/${id}/cancel`,{method:"POST"}),findings:()=>request<any[]>("/api/findings"),finding:(id:string)=>request<any>(`/api/findings/${id}`),
 cfStatus:()=>request<any>("/api/cloudflare/status"),cfAccounts:()=>request<any[]>("/api/cloudflare/accounts"),cfZones:()=>request<any[]>("/api/cloudflare/zones"),cfSecurity:(id:string,scanId?:string)=>request<any>(`/api/cloudflare/zones/${id}/security${scanId?`?scan_id=${scanId}`:""}`),cfSecurityEvents:(id:string,hours=1)=>request<any>(`/api/cloudflare/zones/${id}/security-events?hours=${hours}&limit=50`),cfConnect:(x:any)=>request<any>("/api/cloudflare/connect",{method:"POST",body:JSON.stringify(x)}),
 aiAnalyze:(id:string)=>request<any>(`/api/ai/analyze/${id}`,{method:"POST"}),aiLatest:(id:string)=>request<any>(`/api/ai/analyze/${id}/latest`),generateReport:(id:string,format:string)=>request<any>(`/api/reports/${id}/generate?format=${format}`,{method:"POST"}),
 getReport:async(id:string,format:string)=>{const t=tokens();const h=new Headers();if(t.access)h.set("Authorization",`Bearer ${t.access}`);let r=await fetch(`${API_URL}/api/reports/${id}?format=${format}`,{headers:h,cache:"no-store"});if(r.status===401&&t.refresh){const rr=await fetch(API_URL+"/api/auth/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refresh_token:t.refresh})});if(rr.ok){const x=await rr.json();localStorage.setItem("cs_access",x.access_token);localStorage.setItem("cs_refresh",x.refresh_token);h.set("Authorization",`Bearer ${x.access_token}`);r=await fetch(`${API_URL}/api/reports/${id}?format=${format}`,{headers:h,cache:"no-store"})}}if(!r.ok){let e:any={};try{e=await r.json()}catch{};throw new Error(e.message||e.detail||`HTTP ${r.status}`)}const ct=r.headers.get("content-type")||"";if(ct.includes("application/pdf")||ct.includes("text/csv")||ct.includes("text/html")){return {kind:"blob",blob:await r.blob(),contentType:ct,disposition:r.headers.get("content-disposition")||""}}return {kind:"json",data:await r.json()};},
 adminUpdateUser:(id:string,x:any)=>request<any>(`/api/admin/users/${id}`,{method:"PATCH",body:JSON.stringify(x)}),adminUsers:()=>request<any[]>("/api/admin/users"),adminAudit:()=>request<any[]>("/api/admin/audit-logs"),adminSystem:()=>request<any>("/api/admin/system")
};
export function saveAuth(x:any){localStorage.setItem("cs_access",x.access_token);localStorage.setItem("cs_refresh",x.refresh_token);localStorage.setItem("cs_user",JSON.stringify(x.user))}
export function clearAuth(){localStorage.removeItem("cs_access");localStorage.removeItem("cs_refresh");localStorage.removeItem("cs_user")}
